name: "Actual Budget hdsheena"
description: "Run the latest stable version of Actual Budget."
url: "https://actualbudget.org"
slug: "actualbudget"
init: false
ingress: true
ingress_port: 5007
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
webui: "[PROTO:option_name]://[HOST]:[PORT:5007]"
boot: auto
ports:
  5007/tcp: 5007
image: ghcr.io/actualbudget/actual-server
version: 24.4.0-alpine
